from app.models.user import User
from app.models.ontology import OntologyProject
from app.models.entity import Entity
from app.models.relation import Relation
from app.models.logic import LogicRule
from app.models.action import Action
from app.models.file import UploadedFile
from app.models.prompt import Prompt
from app.models.model_config import ModelConfig
from app.models.extraction_task import ExtractionTask
from app.models.rules_config import RulesConfig